#!/bin/bash


VERSION="0.0.0"

#Set Script Name variable
SCRIPT=`basename ${BASH_SOURCE[0]}`

#Set fonts for Help.
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`


OPTS=`getopt -o Vh --long version,help,no-git,git-name,git-email,no-vim,no-virtualenv -n 'parse-options' -- "$@"`

eval set -- "$OPTS"

PRINT_HELP=false
PRINT_VERSION=false
NO_GIT=false
GIT_NAME=''
GIT_EMAIL=''
NO_VIM=false
NO_VIRTUALENV=false

function print_version() {
  echo -e "$SCRIPT $VERSION"\\n
  exit 0
}

function usage()
{
cat << EOF
Help documentation for ${BOLD}${SCRIPT}.${NORM}
${REV}Basic usage:${NORM} ${BOLD}$SCRIPT [OPTIONS]${NORM}

${BOLD}OPTIONS:${NORM}
  ${BOLD}-h, --help${NORM}
    Print a usage message briefly summarizing these command-line options and exit.
  ${BOLD}-V, --version${NORM}
    Print the version number of ${SCRIPT} to the standard output stream.

  ${BOLD}--no-git${NORM}
    Exclude git configuration.
  ${BOLD}--git-name${NORM}
    Define ${REV}user.name${NORM} for git configuration.
  ${BOLD}--git-email${NORM}
    Define ${REV}user.email${NORM} for git configuration.

  ${BOLD}--no-vim${NORM}
    Do not configure vim.

   ${BOLD}--no-virtualenv${NORM}
    Do not install virtualenv.
 
EOF
exit 1
}


#Check the number of arguments. If none are passed, print help and exit.
NUMARGS=$#
if [ $NUMARGS -eq 0 ]; then
  usage
fi


### Start getopts code ###
while [ $# -gt 0 ]; do
  case $1 in
    -h | --help)
      usage
      ;;
    -V | --version)
      print_version
      ;;
    --no-git) NO_GIT=true ;;
    --no-vim) NO_VIM=true ;;
    --git-name) GIT_NAME=$2; shift; ;;
    --git-email) GIT_EMAIL=$2; shift; ;;
    --no-virtualenv) NO_VIRTUALENV=true ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not recognized."
      echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
      exit 2
      ;; 
  esac
  shift
done
### End getopts code ###


### Start Utilities functions ###
function backup_file() {
  test -e $HOME/$1 && cp -LiR $HOME/$1 $HOME/$1.dotbackup && rm -rf $HOME/$1
  return 1
}

function backup_directory() {
  test -d $HOME/$1.dotbackup && echo -n "~/$1.dotbackup: " && rm -rI $HOME/$1.dotbackup
  test -d $HOME/$1 && cp -LR $HOME/$1 $HOME/$1.dotbackup && rm -rf $HOME/$1
  return 1
}

function link_file() {
  backup_file $2
  ln -s `pwd`/$1 $HOME/$2
}

function link_directory() {
  backup_directory $2
  ln -s `pwd`/$1 $HOME/$2
}

function copy_file() {
  backup_file $2
  cp `pwd`/$1 $HOME/$2
}
### End utilities functions ###

function configure_git() {
  echo "Configuring git..."
  if [ -z "$GIT_NAME" ]; then
    read -p "Git user.name: " GIT_NAME
  fi
  if [ -z "$GIT_EMAIL" ]; then
    read -p "Git user.email: " GIT_EMAIL
  fi
  backup_file .gitconfig
  sed -e 's/\[\[GIT_NAME\]\]/'"$GIT_NAME"'/g' -e 's/\[\[GIT_EMAIL\]\]/'"$GIT_EMAIL"'/g' `pwd`/gitconfig > $HOME/.gitconfig
  copy_file gitignore-global .gitignore
}


function configure_vim() {
  echo "Installing Vim with mode python enabled..."
  ./vim/install_vim.sh
  ./vim/install_pathogen.sh
  ./vim/install_fugitive.sh
  ./vim/install_pep8_pyflakes.sh
  ./vim/install_jedi.sh
  ./vim/install_tasklist.sh
  copy_file vimrc ~/.vimrc
}

function install_virtualenv() {
  echo "Installing virtualenv..."
  ./install_virtualenv.sh
}

### Start main program ###
if [ "$NO_GIT" == false ]; then
  configure_git
fi

if [ "$NO_VIM" == false ]; then
  configure_vim
fi

if [ "$NO_VIRTUALENV" == false ]; then
  install_virtualenv
fi
### End main program ###
